name: adventofcode2023
description: My solutions to Advent of Code 2023
version: 1.0.0
repository: https://github.com/adil192/adventofcode2023

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  dart_numerics: ^0.0.6
  trotter: ^2.2.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  coverage: ^1.7.2
