name: Tests

on:
  workflow_dispatch:
  pull_request:
  push:

env:
  PUB_CACHE: .dart_tool/pub_cache

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1

      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: |
            build
            .dart_tool
          key: ${{ runner.os }}-adventofcode2023

      - run: dart pub get
      - run: dart format --output=none --set-exit-if-changed .
      - run: dart analyze
      - run: dart test
